using FootballManagerSimulator.Helpers;
using FootballManagerSimulator.Interfaces;
using FootballManagerSimulator.Structures;
using Microsoft.Extensions.Options;

namespace FootballManagerSimulator.Factories;

public class LeagueFactory : ILeagueFactory
{
    private readonly IClubHelper ClubHelper;
    private readonly Settings Settings;

    public LeagueFactory(
        IClubHelper clubHelper,
        IOptions<Settings> settings)
    {
        ClubHelper = clubHelper;
        Settings = settings.Value;
    }

    public League CreateLeague(Settings.LeagueModel leagueModel)
    {
        var clubs = Settings.Clubs
            .Where(p => p.LeagueId == leagueModel.Id)
            .Select(p => new Club
            {
                Id = p.Id,
                Name = p.Name
            });

        if (clubs == null || !clubs.Any())
            throw new Exception($"Unable to get clubs by leagueResourceId {leagueModel.Id}");

        var league = new League()
        {
            Id = leagueModel.Id,
            Name = leagueModel.Name,
            Rank = leagueModel.Rank,
            Clubs = clubs.ToList(),
            Fixtures = GenerateNextRoundOfFixtures(clubs.ToList())
        };
        return league;
    }

    public class RandomFixture
    {
        public int WeekNumber { get; set; }
        public DateOnly Date { get; set; }
    }

    //Generated by Chat GPT
    private List<Fixture> GenerateNextRoundOfFixtures(List<Club> clubs)
    {
        var output = new List<Fixture>();

        var numRounds = clubs.Count() - 1;
        var halfSize = clubs.Count() / 2;

        var clubIndices = new List<Club>(clubs);

        clubIndices.RemoveAt(0);

        var clubIdxSize = clubIndices.Count;

        var date = Settings.General.StartDateAsDate.AddDays(2);

        var randomHelpers = new List<RandomFixture>();
        for (int i = 1; i <= numRounds * 2; i++)
        {
            randomHelpers.Add(new RandomFixture
            {
                WeekNumber = i,
                Date = date
            });
            date = date.AddDays(7);
        }
        randomHelpers = randomHelpers.OrderBy(p => RandomNumberHelper.Next()).ToList();

        for (var round = 0; round < numRounds; round++)
        {
            var clubIdx = round % clubIdxSize;

            var randomHelper = randomHelpers.First();
            randomHelpers.Remove(randomHelper);

            output.Add(new Fixture
            {
                HomeClub = ClubHelper.GetClubById(clubs.ElementAt(0).Id),
                AwayClub = ClubHelper.GetClubById(clubIndices[clubIdx].Id),
                WeekNumber = randomHelper.WeekNumber,
                Date = randomHelper.Date
            });

            for (int idx = 1; idx < halfSize; idx++)
            {
                var firstClubIdx = (round + idx) % clubIdxSize;
                var secondClubIdx = (round + clubIdxSize - idx) % clubIdxSize;

                output.Add(new Fixture
                {
                    HomeClub = ClubHelper.GetClubById(clubIndices[firstClubIdx].Id),
                    AwayClub = ClubHelper.GetClubById(clubIndices[secondClubIdx].Id),
                    WeekNumber = randomHelper.WeekNumber,
                    Date = randomHelper.Date
                });
            }

            date = date.AddDays(7);
        }

        for (var round = 0; round < numRounds; round++)
        {
            var randomHelper = randomHelpers.First();
            randomHelpers.Remove(randomHelper);

            var clubIdx = round % clubIdxSize;

            output.Add(new Fixture
            {
                HomeClub = ClubHelper.GetClubById(clubIndices[clubIdx].Id),
                AwayClub = ClubHelper.GetClubById(clubs.ElementAt(0).Id),
                WeekNumber = randomHelper.WeekNumber,
                Date = randomHelper.Date
            });

            for (var idx = 1; idx < halfSize; idx++)
            {
                var firstClubIdx = (round + idx) % clubIdxSize;
                var secondClubIdx = (round + clubIdxSize - idx) % clubIdxSize;

                output.Add(new Fixture
                {
                    HomeClub = ClubHelper.GetClubById(clubIndices[secondClubIdx].Id),
                    AwayClub = ClubHelper.GetClubById(clubIndices[firstClubIdx].Id),
                    WeekNumber = randomHelper.WeekNumber,
                    Date = randomHelper.Date
                });
            }

            date = date.AddDays(7);
        }

        return output.OrderBy(p => p.WeekNumber).ThenBy(p => p.HomeClub.Name).ToList();
    }
}
